// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 05-06-2026, 10:47:35 p. m.
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/plugins/**/*.{js,ts,mjs}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/composables/**/*.{js,ts,mjs}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/utils/**/*.{js,ts,mjs}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/danie/OneDrive/Documentos/GitHub/WEB_EVA2/recetario_web/client/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;